# NeuroVLM Quantitative Metrics — v2 (Semantic Metrics)

Evaluates both generative directions across three datasets.
BLEU / ROUGE have been replaced with meaning-aware metrics (see `why_not_bleu_rouge.md`).

| Direction | Datasets | Modes | Metrics |
|---|---|---|---|
| **Brain → Text** | Networks, PubMed, NeuroVault | Short & Long | **NeuroVLM Latent Sim** *(domain-specific)*, BERTScore F1, Semantic Cosine Sim, cleaned-reference variants, cleaned-minus-raw deltas |
| **Text → Brain** | Networks, PubMed, NeuroVault | — | Pearson *r*, Spearman ρ, Dice (pct-90), BrainSpace spin-test p-value |

**NeuroVLM Latent Similarity** encodes the generated text through NeuroVLM's own SPECTER
encoder + InfoNCE projection head, then measures cosine similarity to the original brain
embedding in the shared latent space — the most model-grounded evaluation available.

```
Prerequisites
pip install neurovlm[metrics,llm]
pip install bert-score sentence-transformers nltk scipy
# Optional, required for exact NCT-style MNI→fsaverage6 spin tests:
pip install neuromaps brainspace
# Ollama (fast path):
ollama pull qwen2.5:3b-instruct
```

In [14]:
import os
os.environ["USE_TF"] = "0"
os.environ["USE_FLAX"] = "0"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

import hashlib
import json
import re
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
import pandas as pd
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

from neurovlm import NeuroVLM
from neurovlm.data import load_dataset, load_latent, load_masker
from neurovlm.metrics import (
    pearson_correlation,
    dice_percentile,
    nct_dice_spin_test_nifti,
    nct_dice_spin_test_surface,
    mni152_to_fsaverage_arrays,
)

# Semantic text metrics
from bert_score import score as bert_score
from sentence_transformers import SentenceTransformer, util as st_util

# Spatial metrics
from scipy.stats import spearmanr

In [15]:
# ── LLM settings ──────────────────────────────────────────────────────────────
LLM_BACKEND = "ollama"               # "ollama" | "huggingface"
LLM_MODEL   = "qwen2.5:3b-instruct"  # Ollama: any pulled model

# ── BERTScore model ───────────────────────────────────────────────────────────
# Best for scientific text; swap for "distilbert-base-uncased" if OOM.
BERTSCORE_MODEL = "microsoft/deberta-xlarge-mnli"

# ── Evaluation budget ─────────────────────────────────────────────────────────
MAX_B2T = 30   # samples per dataset for brain-to-text
MAX_T2B = 50   # samples per dataset for text-to-brain

# ── Retrieval settings ────────────────────────────────────────────────────────
B2T_TOP_K   = 5     # context rows passed to LLM
B2T_SIM_THR = 0.35  # cosine-similarity floor; relaxed if no rows pass
B2T_DATASETS = ["kg_mesh", "cogatlas"]  # retrieval corpora for brain-to-text

# ── Abstract cleaning cache / QC ──────────────────────────────────────────────
CLEAN_GT_SIM_THRESHOLD = 0.85
CLEAN_GT_SPOTCHECK_N = 5
CLEAN_ABSTRACT_PROMPT_VERSION = "v3_no_methods_or_participants"
_EVAL_DIR = Path("docs/03_evaluation") if Path("docs/03_evaluation").exists() else Path(".")
CLEAN_ABSTRACT_CACHE_PATH = _EVAL_DIR / "cleaned_b2t_abstracts_cache.json"

# ── Spatial metric settings ───────────────────────────────────────────────────
DICE_PCT = 90
DICE_SENSITIVITY_PCTS = [80, 85, 90, 95]
SPIN_TEST_N_PERM = 1000
SPIN_TEST_RANDOM_STATE = 13

# NCT-style spin test settings. fsaverage6 corresponds to neuromaps/FreeSurfer
# density "41k". neuromaps wraps the Wu et al. (2018) nonlinear MNI→fsaverage
# registrations via transforms.mni152_to_fsaverage; BrainSpace handles rotations.
SPIN_USE_NEUROMAPS = True
SPIN_FSAVERAGE_DENSITY = "41k"
SPIN_TRANSFORM_METHOD = "linear"

In [16]:
nvlm   = NeuroVLM()
masker = load_masker()

print("Loading sentence transformer...")
_st_model = SentenceTransformer("all-MiniLM-L6-v2")
print("Ready.")

Loading sentence transformer...
Ready.

---
## SPECTER2 Adapter Check

`NeuroVLM._encode_text()` lazy-loads `load_model("specter")`, which resolves to `Specter()`.
In the current codebase, `Specter()` defaults to `model="allenai/specter2_aug2023refresh"` and `adapter="adhoc_query"`; it does **not** default to the proximity adapter (`allenai/specter2`). The InfoNCE projection head was trained downstream of the cached `latent_specter2_adhoc.pt` embeddings, so changing adapters would require at least a distribution sanity check and probably retraining if cosine agreement is low.

In [17]:
from neurovlm.models import Specter

print("NeuroVLM _encode_text() uses load_model('specter') -> Specter().")
print("Current Specter default: model='allenai/specter2_aug2023refresh', adapter='adhoc_query'.")
print("Projection-head training artifacts reference latent_specter2_adhoc.pt, so the head is aligned to adhoc-query embeddings.")


def specter_adapter_cosine_sanity(texts, other_adapter="proximity"):
    """Compare current adhoc-query embeddings against another SPECTER2 adapter.

    High cosine agreement (>0.9) suggests the existing InfoNCE head may remain usable;
    lower agreement means the head is seeing a shifted embedding distribution and should
    be retrained before using that adapter for reported metrics.
    """
    base = Specter(adapter="adhoc_query", device=str(nvlm.device))
    other = Specter(adapter=other_adapter, device=str(nvlm.device))
    with torch.no_grad():
        z_base = F.normalize(base(texts).cpu(), dim=-1)
        z_other = F.normalize(other(texts).cpu(), dim=-1)
    sims = F.cosine_similarity(z_base, z_other).numpy()
    return pd.DataFrame({"text": texts, "adapter": other_adapter, "cosine_to_adhoc": sims})

# Example, intentionally not run automatically because it may download the other adapter:
# sample_texts = [d["long_gt"] for d in pubmed_data_b2t[:3]]
# specter_adapter_cosine_sanity(sample_texts, other_adapter="proximity")

NeuroVLM _encode_text() uses load_model('specter') -> Specter().
Current Specter default: model='allenai/specter2_aug2023refresh', adapter='adhoc_query'.
Projection-head training artifacts reference latent_specter2_adhoc.pt, so the head is aligned to adhoc-query embeddings.

---
## Dataset Preparation

In [18]:
# ── Networks dataset ──────────────────────────────────────────────────────────
SHORT_LABELS = {
    "Language":               "Language network supporting speech comprehension and production.",
    "Auditory":               "Auditory network for acoustic processing and speech encoding.",
    "Default Mode":           "Default mode network for self-referential thought and memory retrieval.",
    "Frontoparietal Control": "Frontoparietal control network for executive function and working memory.",
    "Attention":              "Dorsal attention network for goal-directed visuospatial attention.",
    "Visual":                 "Visual network for feature processing and object recognition.",
    "Motor":                  "Sensorimotor network for movement planning, initiation, and execution.",
    "Cingulo-Opercular":      "Salience network detecting salient events and driving performance monitoring.",
}

LONG_LABELS = {
    "Language": """Language network (LAN; perisylvian language network; frontotemporal language system).Primary regions: left inferior frontal gyrus (Broca's complex), posterior 
                 superior/middle temporal gyrus, temporoparietal junction/angular gyrus. Function: speech/text comprehension and production—semantics, syntax, phonology, and 
                 sentence-level integration.""",

    "Auditory": """ Auditory network (AUD; auditory cortex network). Primary regions: Heschl's gyrus (primary auditory cortex), planum temporale, superior temporal gyrus. Function: acoustic 
        feature analysis (pitch/timbre/timing), auditory scene analysis, early speech-sound encoding, and detection of salient sounds.""",

    "Default Mode": """ Default mode network (DMN; default network; default state network). Primary regions: medial prefrontal cortex, posterior cingulate/precuneus, angular gyrus (lateral parietal).
        Function: internally oriented cognition—autobiographical/episodic memory, self-referential thought, future simulation, social inference, and narrative/semantic integration.""",

    "Frontoparietal Control": """Frontoparietal control network (FPCN; frontoparietal network/FPN; central executive network/CEN). Primary regions: dorsolateral/rostrolateral prefrontal cortex 
        (middle frontal), posterior parietal cortex (inferior parietal/around intraparietal sulcus). Function: goal maintenance and flexible executive control—working memory, 
        rule implementation, planning, and rapid task switching.""",

    "Attention": """ Dorsal attention network. Primary regions: intraparietal sulcus/superior parietal lobule and frontal eye fields. Function: goal-directed, voluntary control of visuospatial 
        attention.""",

    "Visual": """Visual network (VIS; occipital visual network). Primary regions: calcarine cortex/V1 (cuneus/lingual), extrastriate occipital cortex, ventral occipitotemporal visual 
    areas. Function: visual feature processing (form/color/motion), object/scene representations, and visuospatial analysis.""",

    "Motor": """Motor network (motor/sensorimotor network; SMN). Primary regions: primary motor cortex (precentral gyrus), supplementary motor area, premotor cortex; with primary 
    somatosensory cortex (postcentral gyrus) for sensorimotor integration. Function: movement planning, initiation, and execution, plus proprioceptive/tactile feedback used to control 
    actions and maintain body-state representations.""",

    "Cingulo-Opercular": """Salience network (SN; cingulo-opercular network/CON; midcingulo-insular network). Primary regions: anterior insula/frontal operculum, dorsal anterior cingulate/medial frontal cortex. 
    Function: detects behaviorally relevant internal/external events (including interoceptive/affective signals), prioritizes attention and arousal, and drives performance monitoring 
    and control adjustments (error/conflict/uncertainty).""",
}


def _normalize_expected_text(text: str) -> str:
    """Collapse indentation/newlines from triple-quoted expected text."""
    return re.sub(r"\s+", " ", str(text or "")).strip()

_LABEL_TO_DU = {
    "Language":               "LANG",
    "Auditory":               "AUD",
    "Default Mode":           "DN-A",
    "Frontoparietal Control": "FPN-A",
    "Attention":              "dATN-A",
    "Visual":                 "VIS-C",
    "Motor":                  "SMOT-A",
    "Cingulo-Opercular":      "CG-OP",
}

all_net_latents = load_latent("networks_neuro")
du = all_net_latents["Du"]

networks_data = {
    label: {
        "latent":   du[du_key],
        "short_gt": _normalize_expected_text(SHORT_LABELS[label]),
        "long_gt":  _normalize_expected_text(LONG_LABELS[label]),
    }
    for label, du_key in _LABEL_TO_DU.items()
    if du_key in du
}

print(f"Networks loaded: {list(networks_data.keys())}")

Networks loaded: ['Language', 'Auditory', 'Default Mode', 'Frontoparietal Control', 'Attention', 'Visual', 'Motor', 'Cingulo-Opercular']

In [19]:
# ── PubMed dataset ────────────────────────────────────────────────────────────
df_pubs = load_dataset("pubmed_text")
print("PubMed columns:", df_pubs.columns.tolist())
print(f"Total rows: {len(df_pubs)}")

if "split" in df_pubs.columns:
    df_test = df_pubs[df_pubs["split"] == "test"].reset_index(drop=True)
    print(f"Test split rows: {len(df_test)}")
else:
    print("WARNING: no 'split' column found — using full dataset as test proxy.")
    df_test = df_pubs.copy().reset_index(drop=True)

_pmid_col     = "pmid"        if "pmid"        in df_test.columns else df_test.columns[0]
_title_col    = "name"        if "name"        in df_test.columns else "title"
_abstract_col = "description" if "description" in df_test.columns else "abstract"

pubmed_latents, pubmed_pmids = load_latent("pubmed_images")
pubmed_pmids = np.asarray(pubmed_pmids)

mask = np.isin(pubmed_pmids, df_test[_pmid_col].values)
aligned_latents = pubmed_latents[mask]
aligned_pmids   = pubmed_pmids[mask]

pmid_to_row = df_test.set_index(_pmid_col)

pubmed_data = []
for i, pmid in enumerate(aligned_pmids):
    if pmid not in pmid_to_row.index:
        continue
    row      = pmid_to_row.loc[pmid]
    title    = str(row[_title_col])    if _title_col    in row.index else ""
    abstract = str(row[_abstract_col]) if _abstract_col in row.index else ""
    pubmed_data.append({
        "pmid":     pmid,
        "latent":   aligned_latents[i],
        "short_gt": title,
        "long_gt":  abstract,
    })

pubmed_data_b2t = pubmed_data[:MAX_B2T] if MAX_B2T else pubmed_data
pubmed_data_t2b = pubmed_data[:MAX_T2B] if MAX_T2B else pubmed_data

print(f"PubMed B2T samples: {len(pubmed_data_b2t)}")
print(f"PubMed T2B samples: {len(pubmed_data_t2b)}")

PubMed columns: ['pmid', 'pmcid', 'doi', 'name', 'description', 'train', 'test', 'val']
Total rows: 30826
WARNING: no 'split' column found — using full dataset as test proxy.
PubMed B2T samples: 30
PubMed T2B samples: 50

In [20]:
# ── NeuroVault dataset ────────────────────────────────────────────────────────
df_nv      = load_dataset("neurovault_text")
df_nv_meta = load_dataset("neurovault_images_meta")
nv_latents = load_latent("neurovault_images")

print("NeuroVault pub columns:",  df_nv.columns.tolist())
print("NeuroVault meta columns:", df_nv_meta.columns.tolist())
print(f"NV latents shape: {nv_latents.shape}")

_doi_pub  = "doi"      if "doi"      in df_nv.columns      else df_nv.columns[0]
_doi_meta = "doi"      if "doi"      in df_nv_meta.columns else df_nv_meta.columns[0]
_title_nv = "title"    if "title"    in df_nv.columns      else df_nv.columns[1]
_abs_nv   = "abstract" if "abstract" in df_nv.columns      else df_nv.columns[2]

neurovault_data = []
for _, pub_row in df_nv.iterrows():
    doi      = pub_row[_doi_pub]
    title    = str(pub_row[_title_nv])
    abstract = str(pub_row[_abs_nv])

    img_mask    = df_nv_meta[_doi_meta] == doi
    img_indices = np.where(img_mask.values)[0]

    if len(img_indices) == 0 or img_indices[0] >= len(nv_latents):
        continue

    img_idx = int(img_indices[0])
    neurovault_data.append({
        "doi":      doi,
        "latent":   nv_latents[img_idx],
        "short_gt": title,
        "long_gt":  abstract,
    })

neurovault_data_b2t = neurovault_data[:MAX_B2T] if MAX_B2T else neurovault_data
neurovault_data_t2b = neurovault_data[:MAX_T2B] if MAX_T2B else neurovault_data

print(f"NeuroVault B2T samples: {len(neurovault_data_b2t)}")
print(f"NeuroVault T2B samples: {len(neurovault_data_t2b)}")

NeuroVault pub columns: ['doi', 'title', 'abstract']
NeuroVault meta columns: ['Unnamed: 0', 'id', 'collection_id', 'contrast_definition', 'name', 'doi']
NV latents shape: torch.Size([3183, 384])
NeuroVault B2T samples: 30
NeuroVault T2B samples: 50

In [21]:
from neurovlm.llm_summary import _generate_with_ollama, _generate_with_huggingface

_CLEAN_ABSTRACT_SYSTEM = """You convert neuroimaging abstracts into concise finding-only reference text for fair semantic evaluation.

Hard rules:
- Remove all participant/sample language. Do not mention volunteers, patients, subjects, controls, sample size, age, sex, handedness, or demographics.
- Remove all acquisition/procedure details. Do not mention PET, fMRI, MRI, scanner field strength, radiotracers, injections, image acquisition, preprocessing, thresholds, software, or statistical models.
- Remove all numeric result details and inferential statistics. Do not mention p-values, t/F/r values, cluster sizes, coordinates, percentages, timing, doses, or thresholds.
- Remove generic study framing such as "we measured", "we investigated", "the study used", or "activation was measured".
- Preserve only the semantic neuroscience content: brain regions, direction of activation/connectivity if stated, cognitive functions, stimuli/tasks/contrasts in plain language, disorders/conditions, and core findings.
- Do not add facts. Do not preserve unsupported methodological facts just because they are in the original.
- Return 1-4 plain sentences and nothing else.

Example:
Original: Cerebral activation was measured with positron emission tomography in ten human volunteers. The primary auditory cortex showed increased activity in response to noise bursts, whereas acoustically matched speech syllables activated secondary auditory cortices bilaterally. Instructions to make judgments about syllables modulated frontal activity.
Cleaned: Noise bursts preferentially engaged primary auditory cortex, while matched speech syllables engaged bilateral secondary auditory cortices. Judgments about syllables modulated frontal activity."""


def _load_clean_abstract_cache() -> dict:
    if CLEAN_ABSTRACT_CACHE_PATH.exists():
        with CLEAN_ABSTRACT_CACHE_PATH.open("r", encoding="utf-8") as f:
            return json.load(f)
    return {}


def _save_clean_abstract_cache(cache: dict) -> None:
    with CLEAN_ABSTRACT_CACHE_PATH.open("w", encoding="utf-8") as f:
        json.dump(cache, f, indent=2, ensure_ascii=False, sort_keys=True)


def _clean_cache_key(dataset: str, sample_id: str, text: str) -> str:
    digest = hashlib.sha256(str(text or "").encode("utf-8")).hexdigest()[:16]
    return f"{CLEAN_ABSTRACT_PROMPT_VERSION}|{LLM_BACKEND}|{LLM_MODEL}|{dataset}|{sample_id}|{digest}"


def clean_abstract_for_eval(text: str) -> str:
    """Rewrite a scientific abstract into a finding-focused reference for B2T metrics."""
    text = str(text or "").strip()
    if not text or text.lower() == "nan":
        return ""

    messages = [
        {"role": "system", "content": _CLEAN_ABSTRACT_SYSTEM},
        {"role": "user", "content": f"Clean this abstract. Return only the cleaned finding-focused text:\n\n{text}"},
    ]
    if LLM_BACKEND == "ollama":
        return _generate_with_ollama(messages, model_name=LLM_MODEL, verbose=False).strip()
    if LLM_BACKEND == "huggingface":
        return _generate_with_huggingface(messages, model_name=LLM_MODEL, verbose=False).strip()
    raise ValueError(f"Unknown LLM_BACKEND: {LLM_BACKEND}")


def _clean_gt_semantic_sim(original: str, cleaned: str) -> float:
    if not str(original or "").strip() or not str(cleaned or "").strip():
        return np.nan
    emb1 = _st_model.encode(str(original), convert_to_tensor=True)
    emb2 = _st_model.encode(str(cleaned), convert_to_tensor=True)
    return float(st_util.cos_sim(emb1, emb2))


def add_clean_b2t_references(records, dataset, id_key, desc):
    """Attach cleaned references, using a persistent JSON cache to avoid reruns."""
    cache = _load_clean_abstract_cache()
    cache_changed = False
    for d in tqdm(records, desc=desc):
        sample_id = str(d.get(id_key, ""))
        key = _clean_cache_key(dataset, sample_id, d["long_gt"])
        cached = cache.get(key)
        if cached is None:
            cleaned = clean_abstract_for_eval(d["long_gt"])
            cache[key] = {
                "dataset": dataset,
                "sample_id": sample_id,
                "prompt_version": CLEAN_ABSTRACT_PROMPT_VERSION,
                "backend": LLM_BACKEND,
                "model": LLM_MODEL,
                "original": d["long_gt"],
                "cleaned": cleaned,
            }
            cache_changed = True
        else:
            cleaned = cached["cleaned"]

        d["short_gt_clean"] = d["short_gt"]
        d["long_gt_clean"] = cleaned
        d["long_gt_clean_sim"] = _clean_gt_semantic_sim(d["long_gt"], d["long_gt_clean"])
        d["long_gt_clean_flag"] = bool(
            np.isfinite(d["long_gt_clean_sim"]) and d["long_gt_clean_sim"] < CLEAN_GT_SIM_THRESHOLD
        )

    if cache_changed:
        _save_clean_abstract_cache(cache)
    return records

# Networks labels are already clean; only PubMed and NeuroVault abstracts are rewritten.
pubmed_data_b2t = add_clean_b2t_references(pubmed_data_b2t, "pubmed", "pmid", "Cleaning PubMed abstracts")
neurovault_data_b2t = add_clean_b2t_references(neurovault_data_b2t, "neurovault", "doi", "Cleaning NeuroVault abstracts")

_clean_qc_rows = []
for dataset, records in [("pubmed", pubmed_data_b2t), ("neurovault", neurovault_data_b2t)]:
    for i, d in enumerate(records):
        _clean_qc_rows.append({
            "dataset": dataset,
            "sample": str(d.get("pmid", d.get("doi", i))),
            "original": d["long_gt"],
            "cleaned": d["long_gt_clean"],
            "orig_clean_sem_sim": d["long_gt_clean_sim"],
            "needs_manual_review": d["long_gt_clean_flag"],
        })

clean_abstract_qc_df = pd.DataFrame(_clean_qc_rows)
print(f"Cleaned references ready from cache: {CLEAN_ABSTRACT_CACHE_PATH}")
print(f"Manual-review flags: {clean_abstract_qc_df['needs_manual_review'].sum()} / {len(clean_abstract_qc_df)}")
display(clean_abstract_qc_df[["dataset", "sample", "orig_clean_sem_sim", "needs_manual_review"]].round(3))

Cleaning PubMed abstracts:   0%|          | 0/30 [00:00<?, ?it/s]

Cleaning NeuroVault abstracts:   0%|          | 0/30 [00:00<?, ?it/s]

Cleaned references ready from cache: cleaned_b2t_abstracts_cache.json
Manual-review flags: 49 / 60

,dataset,sample,orig_clean_sem_sim,needs_manual_review
0,pubmed,1589767,0.908,False
1,pubmed,8530552,0.702,True
2,pubmed,8624678,0.799,True
3,pubmed,8670634,0.797,True
4,pubmed,8994101,0.689,True
5,pubmed,9038284,0.730,True
6,pubmed,9065511,0.820,True
7,pubmed,9084599,0.764,True
8,pubmed,9106283,0.720,True
9,pubmed,9121583,0.806,True
10,pubmed,9185551,0.822,True
11,pubmed,9256495,0.885,False
12,pubmed,9391021,0.644,True
13,pubmed,9395126,0.780,True
14,pubmed,9395845,0.876,False
15,pubmed,9405692,0.701,True
16,pubmed,9412517,0.842,True
17,pubmed,9465007,0.772,True
18,pubmed,9491989,0.713,True
19,pubmed,9593960,0.829,True
20,pubmed,9600678,0.809,True
21,pubmed,9620697,0.759,True
22,pubmed,9620698,0.768,True
23,pubmed,9620699,0.784,True
24,pubmed,9636217,0.921,False
25,pubmed,9655624,0.792,True
26,pubmed,9714705,0.787,True
27,pubmed,9728909,NaN,False
28,pubmed,9758739,0.738,True
29,pubmed,9770542,0.872,False
30,neurovault,10.1111/cdev.12630,0.741,True
31,neurovault,10.7554/eLife.15192,0.817,True
32,neurovault,10.1073/pnas.0602659103,0.830,True
33,neurovault,10.1073/pnas.1518377113,0.862,False
34,neurovault,10.1038/s41598-017-09744-7,0.827,True
35,neurovault,10.7554/eLife.39681,0.846,True
36,neurovault,10.1177/0956797617728727,0.800,True
37,neurovault,10.1111/desc.12531,0.790,True
38,neurovault,10.1162/jocn_a_01330,0.847,True
39,neurovault,10.1038/s41467-018-08121-w,0.879,False
40,neurovault,10.1093/scan/nsaa050,0.794,True
41,neurovault,10.7554/eLife.22001,0.806,True
42,neurovault,10.12688/f1000research.11964.2,0.733,True
43,neurovault,10.1073/pnas.1710521114,0.736,True
44,neurovault,10.1523/JNEUROSCI.5996-10.2012,0.736,True
45,neurovault,10.1038/s41598-017-08443-7,0.867,False
46,neurovault,10.1073/pnas.1818575116,0.777,True
47,neurovault,10.1093/cercor/bhy281,0.713,True
48,neurovault,10.7554/eLife.39404,0.829,True
49,neurovault,10.1523/JNEUROSCI.2649-13.2013,0.684,True
50,neurovault,10.1126/sciadv.aau3413,0.839,True
51,neurovault,10.1073/pnas.0905267106,0.820,True
52,neurovault,10.1155/2016/2094601,0.737,True
53,neurovault,10.1038/s41467-019-11934-y,0.866,False
54,neurovault,10.1523/JNEUROSCI.1984-18.2018,0.905,False
55,neurovault,10.1162/jocn_a_00520,0.827,True
56,neurovault,10.1002/hbm.24510,0.792,True
57,neurovault,10.1523/ENEURO.0084-17.2017,0.689,True
58,neurovault,10.1038/s41398-019-0670-8,0.775,True
59,neurovault,10.1073/pnas.1608282113,0.839,True

In [22]:
# Spot-check a few cleaned abstracts before trusting cleaned-reference metrics.
# Good rewrites should keep semantic cosine similarity above CLEAN_GT_SIM_THRESHOLD.
spotcheck_clean_abstracts = (
    clean_abstract_qc_df
    .sort_values(["needs_manual_review", "orig_clean_sem_sim"], ascending=[False, True])
    .head(CLEAN_GT_SPOTCHECK_N)
)

for _, row in spotcheck_clean_abstracts.iterrows():
    print("=" * 80)
    print(f"{row['dataset']} | {row['sample']} | sim={row['orig_clean_sem_sim']:.3f} | review={row['needs_manual_review']}")
    print("\nORIGINAL:")
    print(str(row["original"])[:1200])
    print("\nCLEANED:")
    print(str(row["cleaned"])[:1200])

================================================================================
pubmed | 9391021 | sim=0.644 | review=True

ORIGINAL:
To obtain a better understanding of the cortical representation of bimanual coordination, we measured regional cerebral blood flow (rCBF) with 15O-labeled water and positron emission tomography (PET). To detect areas with changes of rCBF during bimanual finger movements of different characteristics, we studied 12 right-handed normal volunteers. A complete session consisted of three rest scans and six scans with acoustically paced (1 Hz) bimanual, mirror, or parallel sequential finger movements. Activation of the right dorsal premotor area (PMd) extending to the posterior supplementary motor area (SMA) was significantly stronger during the parallel movements than during the mirror sequential movements (p < 0.05, at cluster level with correction for multiple comparisons). To determine whether these cortical areas truly represented bimanual coordination, a different group of nine normal volunteers was studied with a different task. Subjects performed acoustically paced (2 Hz) abduction-adduction movements of the index finger, making right only, left only, and bimanual mirror and parallel movements. Activation of the posterior SMA and right PMd was significantly greater during the para

CLEANED:
Parallel finger movements activated the right dorsal premotor area and posterior supplementary motor area significantly more than mirror sequential movements (p < 0.05). Parallel finger movements also activated these areas more than unimanual or mirror unimanual movements (p < 0.01).
================================================================================
neurovault | 10.1523/JNEUROSCI.2649-13.2013 | sim=0.684 | review=True

ORIGINAL:
Cortical and subcortical networks have been identified that are commonly associated with attention and task engagement, along with theories regarding their functional interaction. However, a link between these systems has not yet been demonstrated in healthy humans, primarily because of data acquisition and analysis limitations. We recorded simultaneous EEG–fMRI while subjects performed auditory and visual oddball tasks and used these data to investigate the BOLD correlates of single-trial EEG variability at latencies spanning the trial. We focused on variability along task-relevant dimensions in the EEG for identical stimuli and then combined auditory and visual data at the subject level to spatially and temporally localize brain regions involved in endogenous attentional modulations. Specifically, we found that anterior cingulate cortex (ACC) correlates strongly with both early and late EEG components, whereas brainstem, right middle frontal gyrus (rMFG), and right orbitofrontal cortex (rOFC) correlate significantly only with late components. By orthogonalizing with respect to event-related activity, we found that variability in insula and temporoparietal junction is reflected in

CLEANED:
ACC correlates with early and late EEG components. rMFG and rOFC correlate significantly only with late EEG components. Insula and temporoparietal junction correlate with reaction time variability. Brainstem correlates with residual EEG variability. ACC and rMFG are correlated with both early and late EEG variability. DCM analysis supports reciprocal connections between brainstem and cortical regions, aligning with adaptive gain theory of LC-NE function and P300 EEG response.
================================================================================
neurovault | 10.1523/ENEURO.0084-17.2017 | sim=0.689 | review=True

ORIGINAL:
Large-scale functional networks, as identified through the coordinated activity of spatially distributed brain regions, have become central objects of study in neuroscience because of their contributions to many processing domains. Yet, it remains unclear how these domain-general networks interact with focal brain regions to coordinate thought and action. Here, we investigated how the default-mode network (DMN) and executive control network (ECN), two networks associated with goal-directed behavior, shape task performance through their coupling with other cortical regions several seconds in advance of behavior. We measured these networks' connectivity during an adaptation of the monetary incentive delay (MID) response-time task in which human participants viewed social and nonsocial images (i.e., pictures of faces and landscapes, respectively) while brain activity was measured using fMRI. We found that participants displayed slower reaction times (RTs) subsequent to social trials relative to nonsocial trials. To examine the neural mechanisms driving this subsequent-RT effect, we integrated independent components analysis (ICA) and a network-based psychophysiological interaction (nP

CLEANED:
Default-mode and executive control networks shape task performance by coupling with other cortical regions several seconds prior to behavior onset. Social stimuli lead to increased coupling between fusiform gyrus (FFA) with executive control network relative to default-mode network, correlating with slower reaction times on the following trial.
================================================================================
pubmed | 8994101 | sim=0.689 | review=True

ORIGINAL:
Forty-two patients with acoustic neuroma (AN) were studied to determine whether different types of neuroma could be correlated with specific signs and symptoms of the disease. Based on gadolinium-enhanced TI-weighted MRI sequences, the 42 cases of AN could be divided into three groups, either by size (small: 11.9%, medium: 50%, and large: 38.1%) or by site of origin of the tumour (lateral: 16.7%, intermediate: 69%, and medial: 14.3%). Relations were found between the size and the site of origin of the neuromas and certain clinical, audiological and vestibular findings. The clinical presentation seemed to vary with the site of origin and the size of the tumour: patients with lateral neuromas generally had small tumours, sometimes only located in the internal auditory canal (IAC), and presented early subjective hearing loss while patients with medial neuromas had larger tumours which grew without causing significant audiological symptoms. Normal hearing function was seen only in the patients with medial ANs; however, a significant relation between the size or the site of origin of the AN and the average hearing threshold was not demonstrated. The sensitivity of the stapedial reflex t

CLEANED:
AN size and site of origin correlated with clinical, audiological, and vestibular findings: lateral ANs were associated with smaller tumours causing early hearing loss, while medial ANs had larger tumours without significant auditory symptoms. Treated as separate entities by their size and site, SR sensitivity differed; BAEP anomalies did not correlate with size or site. Anomalies in BAEPs and vestibular tests were more frequent in large and lateral ANs respectively, indicating optimal identification through these combination tests.
================================================================================
pubmed | 9405692 | sim=0.701 | review=True

ORIGINAL:
A number of neuroimaging findings have been interpreted as evidence that the left inferior frontal gyrus (IFG) subserves retrieval of semantic knowledge. We provide a fundamentally different interpretation, that it is not retrieval of semantic knowledge per se that is associated with left IFG activity but rather selection of information among competing alternatives from semantic memory. Selection demands were varied across three semantic tasks in a single group of subjects. Functional magnetic resonance imaging signal in overlapping regions of left IFG was dependent on selection demands in all three tasks. In addition, the degree of semantic processing was varied independently of selection demands in one of the tasks. The absence of left IFG activity for this comparison counters the argument that the effects of selection can be attributed solely to variations in degree of semantic retrieval. Our findings suggest that it is selection, not retrieval, of semantic knowledge that drives activity in the left IFG.

CLEANED:
Left IFG activity depends on selection demands across different semantic tasks, opposing the notion that left IFG is exclusively involved in semantic retrieval.

---
## Part A — Brain-to-Text (BERTScore, Semantic Sim, METEOR, NeuroVLM Latent Sim)

For each brain image we:
1. Retrieve the most similar text entries via contrastive similarity.
2. Generate with the LLM twice — once in **short** mode, once in **long** mode.
3. Compute BERTScore, sentence-level cosine similarity, and NeuroVLM latent similarity.

**NeuroVLM Latent Similarity** is the most meaningful metric here:
it encodes the generated text through NeuroVLM's own SPECTER + projection head
and computes cosine similarity against the original brain image embedding
in the shared latent space. A paraphrase that preserves meaning will score
as highly as a literal match — and the metric is grounded in the model's own
representation, not an external embedding space.

See `why_not_bleu_rouge.md` for the rationale for dropping BLEU / ROUGE.

In [23]:
import traceback


def _semantic_sim(gen: str, gt: str) -> float:
    emb1 = _st_model.encode(gen, convert_to_tensor=True)
    emb2 = _st_model.encode(gt,  convert_to_tensor=True)
    return float(st_util.cos_sim(emb1, emb2))


def _bertscore_single(generated: str, reference: str):
    P, R, F1 = bert_score(
        cands=[generated],
        refs=[reference],
        lang="en",
        model_type=BERTSCORE_MODEL,
        verbose=False,
    )
    return float(P[0]), float(R[0]), float(F1[0])


def _nvlm_latent_sim(brain_query_emb: torch.Tensor, generated: str) -> float:
    """Cosine similarity in NeuroVLM's shared latent space."""
    nvlm._ensure_projection_heads()
    with torch.no_grad():
        raw_emb = nvlm._encode_text(generated)                         # (1, 768)
        z_text  = nvlm._proj_head_text_infonce(raw_emb.to(nvlm.device)) # project
        z_text  = F.normalize(z_text, dim=-1).cpu()                    # normalise
    z_brain = brain_query_emb.cpu()
    if z_brain.dim() == 1:
        z_brain = z_brain.unsqueeze(0)
    return float(F.cosine_similarity(z_brain, z_text))


def _b2t_once(table, user_prompt, gt_text, max_tokens, brain_query_emb, gt_text_clean=None):
    """Generate one B2T response and compute semantic metrics against raw and cleaned refs."""
    generated = nvlm.generate_llm_response(
        backend=LLM_BACKEND,
        model_name=LLM_MODEL,
        table=table,
        user_prompt=user_prompt,
        max_new_tokens=max_tokens,
        verbose=False,
    )

    bert_p, bert_r, bert_f1 = _bertscore_single(generated, gt_text)
    sem_sim = _semantic_sim(generated, gt_text)
    nvlm_sim = _nvlm_latent_sim(brain_query_emb, generated)

    rec = {
        "generated":  generated,
        "gt_text":    gt_text,
        "gt_text_clean": gt_text_clean if gt_text_clean is not None else gt_text,
        "bert_p":     bert_p,
        "bert_r":     bert_r,
        "bert_f1":    bert_f1,
        "sem_sim":    sem_sim,
        "nvlm_sim":   nvlm_sim,
    }

    if gt_text_clean is not None and gt_text_clean != gt_text:
        clean_p, clean_r, clean_f1 = _bertscore_single(generated, gt_text_clean)
        rec.update({
            "bert_p_clean":  clean_p,
            "bert_r_clean":  clean_r,
            "bert_f1_clean": clean_f1,
            "sem_sim_clean": _semantic_sim(generated, gt_text_clean),
        })
    else:
        rec.update({
            "bert_p_clean":  bert_p,
            "bert_r_clean":  bert_r,
            "bert_f1_clean": bert_f1,
            "sem_sim_clean": sem_sim,
        })

    return rec


def _format_context_summary(table):
    lines = []
    for _, row in table.iterrows():
        ds  = row.get("dataset", "?")
        ttl = str(row.get("title", "")).strip()
        sim = row.get("cosine_similarity", float("nan"))
        lines.append(f"  [{ds}] (sim={sim:.3f}) {ttl}")
    return "\n".join(lines)


def run_b2t(name, latent, short_gt, long_gt,
            short_prompt, long_prompt="",
            short_tokens=64, long_tokens=512,
            short_gt_clean=None, long_gt_clean=None):
    try:
        result    = nvlm.brain(latent).to_text(datasets=B2T_DATASETS)
        all_table = result.top_k(B2T_TOP_K)  # top-k per dataset
        table     = all_table[all_table["cosine_similarity"] > B2T_SIM_THR]
        if table.empty:
            table = all_table
        if len(table) > B2T_TOP_K:
            table = table.nlargest(B2T_TOP_K, "cosine_similarity").reset_index(drop=True)

        context_summary = _format_context_summary(table)
        brain_query_emb = result.query_embeddings

        records = []
        for mode, prompt, gt, gt_clean, tokens in [
            ("short", short_prompt, short_gt, short_gt_clean, short_tokens),
            ("long",  long_prompt,  long_gt,  long_gt_clean,  long_tokens),
        ]:
            rec = _b2t_once(table, prompt, gt, tokens, brain_query_emb, gt_text_clean=gt_clean)
            rec["name"]            = name
            rec["mode"]            = mode
            rec["context_summary"] = context_summary
            records.append(rec)

        return records

    except Exception as e:
        print(f"\n[B2T error] {name}: {type(e).__name__}: {e}")
        traceback.print_exc()
        return []


def show_b2t_texts(df, max_gt_chars=300, max_gen_chars=300):
    sep = "-" * 72
    prev_name = None
    for _, row in df.iterrows():
        name  = row.get("name", "?")
        mode  = row.get("mode", "?")
        gen   = str(row.get("generated",       "")).strip()
        gt    = str(row.get("gt_text",         "")).strip()
        gt_c  = str(row.get("gt_text_clean",   "")).strip()
        ctx   = str(row.get("context_summary", "")).strip()
        bf1   = row.get("bert_f1",  float("nan"))
        bf1c  = row.get("bert_f1_clean", float("nan"))
        sim   = row.get("sem_sim",  float("nan"))
        simc  = row.get("sem_sim_clean", float("nan"))
        nvs   = row.get("nvlm_sim", float("nan"))

        print(sep)
        if name != prev_name and ctx:
            print(f"[{name}]  — retrieved context:")
            print(ctx)
            prev_name = name

        print(f"  mode={mode}   BERTScore-F1={bf1:.3f} / clean={bf1c:.3f}  "
              f"SemanticSim={sim:.3f} / clean={simc:.3f}  NeuroVLM-Sim={nvs:.3f}")
        print(f"  EXPECTED : {gt[:max_gt_chars]}{'…' if len(gt) > max_gt_chars else ''}")
        if gt_c and gt_c != gt:
            print(f"  CLEAN GT : {gt_c[:max_gt_chars]}{'…' if len(gt_c) > max_gt_chars else ''}")
        print(f"  GENERATED: {gen[:max_gen_chars]}{'…' if len(gen) > max_gen_chars else ''}")
    print(sep)


# ── Prompts ────────────────────────────────────────────────────────────────────
SHORT_PROMPT_GENERAL = (
    "Reply with a single concise sentence (10-20 words) naming the main "
    "cognitive function or brain network. Output only that sentence."
)

SHORT_PROMPT_PUBMED = (
    "Generate ONLY a paper title (6-12 words) for the neuroimaging study this "
    "brain activation pattern represents. Output the title only — no abstract, "
    "no explanation."
)

LONG_PROMPT = ""

### A.1 Networks

In [24]:
b2t_networks_records = []

for net_name, d in tqdm(networks_data.items(), desc="Networks B2T"):
    recs = run_b2t(
        name         = net_name,
        latent       = d["latent"],
        short_gt     = d["short_gt"],
        long_gt      = d["long_gt"],
        short_prompt = SHORT_PROMPT_GENERAL,
        long_prompt  = LONG_PROMPT,
    )
    b2t_networks_records.extend(recs)

print(f"\nRecords collected: {len(b2t_networks_records)}")

b2t_net_df = pd.DataFrame(b2t_networks_records)

if b2t_net_df.empty:
    print("No records — check the [B2T error] messages above.")
else:
    cols = ["name", "mode", "bert_f1", "bert_p", "bert_r", "sem_sim", "nvlm_sim"]
    display(b2t_net_df[cols].round(3))
    print()
    show_b2t_texts(b2t_net_df)

Networks B2T:   0%|          | 0/8 [00:00<?, ?it/s]

There are adapters available but none are activated for the forward pass.

Records collected: 16

                      name   mode  bert_f1  bert_p  bert_r  sem_sim  nvlm_sim
0                 Language  short    0.697   0.660   0.738    0.625     0.331
1                 Language   long    0.606   0.571   0.646    0.788     0.393
2                 Auditory  short    0.707   0.689   0.725    0.595     0.383
3                 Auditory   long    0.542   0.492   0.603    0.620     0.463
4             Default Mode  short    0.726   0.691   0.766    0.646     0.363
5             Default Mode   long    0.550   0.495   0.620    0.826     0.362
6   Frontoparietal Control  short    0.711   0.702   0.719    0.559     0.362
7   Frontoparietal Control   long    0.511   0.493   0.530    0.559     0.353
8                Attention  short    0.736   0.722   0.751    0.729     0.298
9                Attention   long    0.562   0.490   0.659    0.742     0.382
10                  Visual  short    0.704   0.692   0.716    0.443     0.371
11                  Visual   long    0.553   0.530   0.579    0.558     0.387
12                   Motor  short    0.695   0.675   0.717    0.645     0.454
13                   Motor   long    0.556   0.523   0.593    0.668     0.426
14       Cingulo-Opercular  short    0.608   0.616   0.601    0.232    -0.111
15       Cingulo-Opercular   long    0.514   0.479   0.555    0.560     0.355

------------------------------------------------------------------------
[Language]  — retrieved context:
[kg_mesh] (sim=0.426) language network
  [kg_mesh] (sim=0.413) language abilities
  [kg_mesh] (sim=0.408) expressive language
  [kg_mesh] (sim=0.402) superior temporal regions
  [kg_mesh] (sim=0.396) frontotemporal regions
  mode=short   BERTScore-F1=0.697 / clean=0.697  SemanticSim=0.625 / clean=0.625  NeuroVLM-Sim=0.331
  EXPECTED : Language network supporting speech comprehension and production.
  GENERATED: The primary cognitive function is linguistic communication enabled by the language network.
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.606 / clean=0.606  SemanticSim=0.788 / clean=0.788  NeuroVLM-Sim=0.393
  EXPECTED : Language network (LAN; perisylvian language network; frontotemporal language system).Primary regions: left inferior frontal gyrus (Broca's complex), posterior superior/middle temporal gyrus, temporoparietal junction/angular gyrus. Function: speech/text comprehension and production—semantics, syntax,…
  GENERATED: The language network is a complex neural system comprising multiple brain regions including the left inferior frontal gyrus and the temporal lobe, which collaborate to facilitate speech production, comprehension, and communication. This network is integral to language abilities, encompassing cogniti…
------------------------------------------------------------------------
[Auditory]  — retrieved context:
[cogatlas] (sim=0.438) auditory stream segregation
  [cogatlas] (sim=0.431) auditory encoding
  [cogatlas] (sim=0.431) music cognition
  [kg_mesh] (sim=0.424) auditory cortex
  [cogatlas] (sim=0.424) acoustic phonetic processing
  mode=short   BERTScore-F1=0.707 / clean=0.707  SemanticSim=0.595 / clean=0.595  NeuroVLM-Sim=0.383
  EXPECTED : Auditory network for acoustic processing and speech encoding.
  GENERATED: Auditory stream segregation is a fundamental aspect of hearing and speech perception.
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.542 / clean=0.542  SemanticSim=0.620 / clean=0.620  NeuroVLM-Sim=0.463
  EXPECTED : Auditory network (AUD; auditory cortex network). Primary regions: Heschl's gyrus (primary auditory cortex), planum temporale, superior temporal gyrus. Function: acoustic feature analysis (pitch/timbre/timing), auditory scene analysis, early speech-sound encoding, and detection of salient sounds.
  GENERATED: Auditory stream segregation refers to the perceptual grouping of sounds into distinct representations of objects in an acoustic environment, a foundational process for hearing and speech perception. This function is closely linked with auditory encoding, which involves storing auditory information w…
------------------------------------------------------------------------
[Default Mode]  — retrieved context:
[kg_mesh] (sim=0.571) dmn regions
  [kg_mesh] (sim=0.565) posterior default mode
  [kg_mesh] (sim=0.562) mode network connectivity
  [kg_mesh] (sim=0.542) anterior default mode
  [kg_mesh] (sim=0.538) anterior dmn
  mode=short   BERTScore-F1=0.726 / clean=0.726  SemanticSim=0.646 / clean=0.646  NeuroVLM-Sim=0.363
  EXPECTED : Default mode network for self-referential thought and memory retrieval.
  GENERATED: The Default Mode Network (DMN) is a key brain network associated with self-referential thinking during rest.
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.550 / clean=0.550  SemanticSim=0.826 / clean=0.826  NeuroVLM-Sim=0.362
  EXPECTED : Default mode network (DMN; default network; default state network). Primary regions: medial prefrontal cortex, posterior cingulate/precuneus, angular gyrus (lateral parietal). Function: internally oriented cognition—autobiographical/episodic memory, self-referential thought, future simulation, socia…
  GENERATED: The Default Mode Network (DMN) is a complex network of interconnected brain areas that are active during internally focused cognitive tasks and rest states. It includes the medial prefrontal cortex, which shows reduced activity during task-oriented cognition as evidenced by the evidence row at rank …
------------------------------------------------------------------------
[Frontoparietal Control]  — retrieved context:
[kg_mesh] (sim=0.383) attentional networks
  [kg_mesh] (sim=0.375) attention-based
  [kg_mesh] (sim=0.370) working memory network
  [kg_mesh] (sim=0.364) attentional network
  [kg_mesh] (sim=0.359) attentional focus
  mode=short   BERTScore-F1=0.711 / clean=0.711  SemanticSim=0.559 / clean=0.559  NeuroVLM-Sim=0.362
  EXPECTED : Frontoparietal control network for executive function and working memory.
  GENERATED: Attentional networks orchestrate focused cognitive processing and resource allocation.
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.511 / clean=0.511  SemanticSim=0.559 / clean=0.559  NeuroVLM-Sim=0.353
  EXPECTED : Frontoparietal control network (FPCN; frontoparietal network/FPN; central executive network/CEN). Primary regions: dorsolateral/rostrolateral prefrontal cortex (middle frontal), posterior parietal cortex (inferior parietal/around intraparietal sulcus). Function: goal maintenance and flexible executi…
  GENERATED: Attentional networks represent a specialized set of interconnected brain regions that collaborate to direct and maintain focused attention on specific stimuli or information, essential for maintaining cognitive performance across various tasks. This network includes the prefrontal cortex, parietal l…
------------------------------------------------------------------------
[Attention]  — retrieved context:
[kg_mesh] (sim=0.349) dorsal attention networks
  [cogatlas] (sim=0.332) visuospatial sketch pad
  [kg_mesh] (sim=0.332) spatial processing
  [kg_mesh] (sim=0.328) dorsal attention
  [kg_mesh] (sim=0.326) lateral intraparietal
  mode=short   BERTScore-F1=0.736 / clean=0.736  SemanticSim=0.729 / clean=0.729  NeuroVLM-Sim=0.298
  EXPECTED : Dorsal attention network for goal-directed visuospatial attention.
  GENERATED: Dorsal attention networks direct external focus and guide cognitive operations.
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.562 / clean=0.562  SemanticSim=0.742 / clean=0.742  NeuroVLM-Sim=0.382
  EXPECTED : Dorsal attention network. Primary regions: intraparietal sulcus/superior parietal lobule and frontal eye fields. Function: goal-directed, voluntary control of visuospatial attention.
  GENERATED: Dorsal Attention Networks (DAN) are a component of the brain's network involved in directing attention to specific locations in space and often co-occur with frontoparietal regions. These networks are closely linked with spatial processing, which is fundamental for understanding and manipulating spa…
------------------------------------------------------------------------
[Visual]  — retrieved context:
[cogatlas] (sim=0.413) visual number recognition
  [kg_mesh] (sim=0.413) human visual cortex
  [cogatlas] (sim=0.411) visual letter recognition
  [cogatlas] (sim=0.411) visual recognition
  [kg_mesh] (sim=0.407) flicker fusion
  mode=short   BERTScore-F1=0.704 / clean=0.704  SemanticSim=0.443 / clean=0.443  NeuroVLM-Sim=0.371
  EXPECTED : Visual network for feature processing and object recognition.
  GENERATED: Visual number and letter recognition rely on the human visual cortex.
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.553 / clean=0.553  SemanticSim=0.558 / clean=0.558  NeuroVLM-Sim=0.387
  EXPECTED : Visual network (VIS; occipital visual network). Primary regions: calcarine cortex/V1 (cuneus/lingual), extrastriate occipital cortex, ventral occipitotemporal visual areas. Function: visual feature processing (form/color/motion), object/scene representations, and visuospatial analysis.
  GENERATED: Visual number recognition is the process of identifying and categorizing visually presented numerical stimuli without a specific task-defined context. This function relies heavily on the human visual cortex, which includes areas like Primary Visual Cortex (V1) that are crucial for processing visual …
------------------------------------------------------------------------
[Motor]  — retrieved context:
[kg_mesh] (sim=0.460) sensorimotor cortex
  [kg_mesh] (sim=0.457) primary sensorimotor cortex
  [kg_mesh] (sim=0.446) forelimb
  [cogatlas] (sim=0.439) motor control
  [kg_mesh] (sim=0.438) electromyography
  mode=short   BERTScore-F1=0.695 / clean=0.695  SemanticSim=0.645 / clean=0.645  NeuroVLM-Sim=0.454
  EXPECTED : Sensorimotor network for movement planning, initiation, and execution.
  GENERATED: The sensorimotor cortex coordinates sensory processing and voluntary motor activities.
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.556 / clean=0.556  SemanticSim=0.668 / clean=0.668  NeuroVLM-Sim=0.426
  EXPECTED : Motor network (motor/sensorimotor network; SMN). Primary regions: primary motor cortex (precentral gyrus), supplementary motor area, premotor cortex; with primary somatosensory cortex (postcentral gyrus) for sensorimotor integration. Function: movement planning, initiation, and execution, plus propr…
  GENERATED: The sensorimotor cortex is a critical region of the brain involved in processing sensory information and coordinating voluntary motor activities across different stages, including adulthood and adolescence for both males and females. This cortical network encompasses the primary sensorimotor cortex,…
------------------------------------------------------------------------
[Cingulo-Opercular]  — retrieved context:
[kg_mesh] (sim=0.341) mirror neurons
  [kg_mesh] (sim=0.299) mid-cingulate
  [kg_mesh] (sim=0.293) weapons
  [kg_mesh] (sim=0.268) top-down control
  [kg_mesh] (sim=0.265) posterior insular
  mode=short   BERTScore-F1=0.608 / clean=0.608  SemanticSim=0.232 / clean=0.232  NeuroVLM-Sim=-0.111
  EXPECTED : Salience network detecting salient events and driving performance monitoring.
  GENERATED: Mirror neurons orchestrate social cognition through complex neural networks.
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.514 / clean=0.514  SemanticSim=0.560 / clean=0.560  NeuroVLM-Sim=0.355
  EXPECTED : Salience network (SN; cingulo-opercular network/CON; midcingulo-insular network). Primary regions: anterior insula/frontal operculum, dorsal anterior cingulate/medial frontal cortex. Function: detects behaviorally relevant internal/external events (including interoceptive/affective signals), priorit…
  GENERATED: Mirror neurons are specialized excitatory cortical neurons found primarily in the premotor cortex and associated regions of the brain that exhibit a unique property—they fire both when an individual performs a specific action and observes or thinks about performing the same action. This dual activat…
------------------------------------------------------------------------

### A.2 PubMed

*Short* → LLM generates a title, evaluated against the real title.  
*Long* → LLM generates freely, evaluated against the abstract.

In [25]:
b2t_pubmed_records = []

for d in tqdm(pubmed_data_b2t, desc="PubMed B2T"):
    recs = run_b2t(
        name           = str(d["pmid"]),
        latent         = d["latent"],
        short_gt       = d["short_gt"],
        long_gt        = d["long_gt"],
        short_gt_clean = d.get("short_gt_clean"),
        long_gt_clean  = d.get("long_gt_clean"),
        short_prompt   = SHORT_PROMPT_PUBMED,
        long_prompt    = LONG_PROMPT,
        short_tokens   = 48,
        long_tokens    = 512,
    )
    b2t_pubmed_records.extend(recs)

print(f"\nRecords collected: {len(b2t_pubmed_records)}")

b2t_pubmed_df = pd.DataFrame(b2t_pubmed_records)

if b2t_pubmed_df.empty:
    print("No records — check the [B2T error] messages above.")
else:
    display(b2t_pubmed_df.groupby("mode")[["bert_f1", "bert_f1_clean", "sem_sim", "sem_sim_clean", "nvlm_sim"]].mean().round(3))
    print()
    show_b2t_texts(b2t_pubmed_df)

PubMed B2T:   0%|          | 0/30 [00:00<?, ?it/s]

Warning: Empty reference sentence detected; setting raw BERTScores to 0.

Records collected: 60

       bert_f1  bert_f1_clean  sem_sim  sem_sim_clean  nvlm_sim
mode
long     0.504          0.487    0.398          0.355     0.345
short    0.602          0.602    0.391          0.391     0.310

------------------------------------------------------------------------
[1589767]  — retrieved context:
[cogatlas] (sim=0.479) word pronunciation
  [kg_mesh] (sim=0.469) native language
  [cogatlas] (sim=0.467) language processing
  [kg_mesh] (sim=0.463) language dominance
  [kg_mesh] (sim=0.463) natural speech
  mode=short   BERTScore-F1=0.633 / clean=0.633  SemanticSim=0.671 / clean=0.671  NeuroVLM-Sim=0.355
  EXPECTED : Lateralization of phonetic and pitch discrimination in speech processing.
  GENERATED: Pronunciation in Language Processing: Native Acquisition and Dominant Hemisphere Function
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.515 / clean=0.522  SemanticSim=0.554 / clean=0.583  NeuroVLM-Sim=0.395
  EXPECTED : Cerebral activation was measured with positron emission tomography in ten human volunteers. The primary auditory cortex showed increased activity in response to noise bursts, whereas acoustically matched speech syllables activated secondary auditory cortices bilaterally. Instructions to make judgmen…
  CLEAN GT : Noise bursts activated primary auditory cortex, while speech syllables engaged bilateral secondary auditory cortices. Judgments on speech attributes activated specific lateralized neural systems. Discriminating phonetic structure increased activity in left Broca's area, suggesting articulatory recod…
  GENERATED: Word pronunciation is the act or result of producing sounds of speech through articulation, stress, and intonation; it forms a foundational component in language processing. This cognitive function significantly influences how individuals use their native languages correctly and appropriately. Suppo…
------------------------------------------------------------------------
[8530552]  — retrieved context:
[kg_mesh] (sim=0.436) high fidelity simulation training
  [kg_mesh] (sim=0.432) procedural sedation
  [kg_mesh] (sim=0.427) simulation training
  [kg_mesh] (sim=0.422) succinylcholine
  [kg_mesh] (sim=0.419) chemotherapy, cancer, regional perfusion
  mode=short   BERTScore-F1=0.574 / clean=0.574  SemanticSim=0.093 / clean=0.093  NeuroVLM-Sim=0.387
  EXPECTED : Frequency-dependent changes of regional cerebral blood flow during finger movements.
  GENERATED: High Fidelity Simulation Training: Sedation and Anesthesia in Medical Simulations
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.491 / clean=0.474  SemanticSim=0.256 / clean=0.199  NeuroVLM-Sim=0.334
  EXPECTED : To study the effect of the repetition rate of a simple movement on the distribution and magnitude of neuronal recruitment, we measured regional CBF (rCBF) in eight normal volunteers, using positron emission tomography and 15O-labeled water. An auditory-cued, repetitive flexion movement of the right …
  CLEAN GT : Very slow movement rates did not activate left primary sensorimotor cortex. Activation of right cerebellum occurred between slow and fast movement rates but not at very fast rates. Very fast rates showed no further increase in activation compared to fast rates. Changes in posterior supplementary mot…
  GENERATED: High Fidelity Simulation Training is a neuroimaging-retrieval evidence-based model of advanced medical training techniques that utilize realistic, technology-driven scenarios for healthcare professionals to enhance their clinical competence and patient care skills. This includes the use of sophistic…
------------------------------------------------------------------------
[8624678]  — retrieved context:
[kg_mesh] (sim=0.402) speech-in-noise
  [kg_mesh] (sim=0.400) speech reception threshold test
  [cogatlas] (sim=0.400) speech perception
  [kg_mesh] (sim=0.398) speech discrimination tests
  [kg_mesh] (sim=0.393) language control
  mode=short   BERTScore-F1=0.522 / clean=0.522  SemanticSim=0.176 / clean=0.176  NeuroVLM-Sim=0.366
  EXPECTED : Noun and verb retrieval by normal subjects. Studies with PET.
  GENERATED: Speech-in-Noise: Cognitive Framework Underlying Auditory Comprehension in Background Noise
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.513 / clean=0.494  SemanticSim=0.268 / clean=0.287  NeuroVLM-Sim=0.367
  EXPECTED : PET activation studies identify significant local changes in regional cerebral blood flow (rCBF) in contrasts of behavioural tasks with control states, and these local changes identify net changes in local synaptic activity. A number of studies on word retrieval have all demonstrated left frontal (d…
  CLEAN GT : Left frontal (dorsolateral and medial) regions show extensive activation during word retrieval tasks. Left posterior temporal lobe shows variably deactivation, no response or activation depending on control states contrasted. Semantic processing likely involves left inferolateral temporal cortex and…
  GENERATED: Speech-in-noise is a cognitive construct that describes the impairment in an individual's ability to understand spoken words when background noise is present, encompassing various methods used to assess this condition such as speech reception threshold tests and speech discrimination tests. These pr…
------------------------------------------------------------------------
[8670634]  — retrieved context:
[kg_mesh] (sim=0.387) multitasking behavior
  [kg_mesh] (sim=0.369) working memory network
  [kg_mesh] (sim=0.352) working memory tasks
  mode=short   BERTScore-F1=0.584 / clean=0.584  SemanticSim=0.351 / clean=0.351  NeuroVLM-Sim=0.387
  EXPECTED : Dissociating verbal and spatial working memory using PET.
  GENERATED: Cognitive Flexibility Underlying Multitasking Behavior
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.488 / clean=0.512  SemanticSim=0.542 / clean=0.522  NeuroVLM-Sim=0.401
  EXPECTED : Three experiments used position emission tomography (PET) to study the neural basis of human working memory. These studies ask whether different neural circuits underly verbal and spatial memory. In Experiment 1, subjects had to retain for 3 sec. either the names of four letters (verbal memory) or t…
  CLEAN GT : Verbal memory engaged primarily left-hemisphere regions, while spatial memory engaged right-hemisphere regions. Spatial memory showed bilateral activation with more in the right hemisphere. Continuous vs discrete verbal tasks activated similar regions. Different neural structures underlie verbal and…
  GENERATED: Multitasking Behavior is a cognitive construct involving the simultaneous performance of multiple tasks, observable in humans across various age groups and genders. This process engages regions such as the prefrontal cortex, parietal lobes, and basal ganglia within the working memory network, which …
------------------------------------------------------------------------
[8994101]  — retrieved context:
[kg_mesh] (sim=0.534) surgical equipment
  [kg_mesh] (sim=0.529) acetylene
  [kg_mesh] (sim=0.522) equipment and supplies, hospital
  [kg_mesh] (sim=0.522) hospitals, packaged
  [kg_mesh] (sim=0.519) cellular neural networks, computer
  mode=short   BERTScore-F1=0.632 / clean=0.632  SemanticSim=0.349 / clean=0.349  NeuroVLM-Sim=0.443
  EXPECTED : Acoustic neuroma: correlations between morphology and otoneurological manifestations.
  GENERATED: Surgical Equipment in Neuroimaging Contexts
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.490 / clean=0.486  SemanticSim=0.183 / clean=0.094  NeuroVLM-Sim=0.475
  EXPECTED : Forty-two patients with acoustic neuroma (AN) were studied to determine whether different types of neuroma could be correlated with specific signs and symptoms of the disease. Based on gadolinium-enhanced TI-weighted MRI sequences, the 42 cases of AN could be divided into three groups, either by siz…
  CLEAN GT : AN size and site of origin correlated with clinical, audiological, and vestibular findings: lateral ANs were associated with smaller tumours causing early hearing loss, while medial ANs had larger tumours without significant auditory symptoms. Treated as separate entities by their size and site, SR …
  GENERATED: Surgical Equipment is a key component in the medical field, particularly in invasive procedures such as surgeries and other diagnostic interventions that require precise instruments. This category includes tools like scalpels, sutures, and endoscopes used during surgical operations and interventiona…
------------------------------------------------------------------------
[9038284]  — retrieved context:
[cogatlas] (sim=0.383) central executive
  [kg_mesh] (sim=0.379) working memory tasks
  [kg_mesh] (sim=0.364) working memory network
  [kg_mesh] (sim=0.364) multitasking behavior
  [kg_mesh] (sim=0.362) left frontoparietal network
  mode=short   BERTScore-F1=0.683 / clean=0.683  SemanticSim=0.536 / clean=0.536  NeuroVLM-Sim=0.350
  EXPECTED : A parametric study of prefrontal cortex involvement in human working memory.
  GENERATED: The Central Executive Network and Its Role in Cognitive Flexibility
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.577 / clean=0.571  SemanticSim=0.579 / clean=0.513  NeuroVLM-Sim=0.390
  EXPECTED : Although recent neuroimaging studies suggest that prefrontal cortex (PFC) is involved in working memory (WM), the relationship between PFC activity and memory load has not yet been well-described in humans. Here we use functional magnetic resonance imaging (fMRI) to probe PFC activity during a seque…
  CLEAN GT : Dorsolateral and left inferior PFC exhibit linear activity relationship with memory load during sequential letter task. Activity in these regions correlated with behavioral measure indexing WM function. Additional regions also show a linear relationship with memory load.
  GENERATED: Central executive is a theoretical cognitive system responsible for the management of executive functions including planning, working memory, attention, problem-solving, reasoning, and inhibitory control. This central executive network interacts closely with the working memory network, which involve…
------------------------------------------------------------------------
[9065511]  — retrieved context:
[kg_mesh] (sim=0.304) contactins
  [kg_mesh] (sim=0.297) spatial processing
  [kg_mesh] (sim=0.294) right temporoparietal junction
  [kg_mesh] (sim=0.286) spatial behavior
  [kg_mesh] (sim=0.282) trypanosomiasis, african
  mode=short   BERTScore-F1=0.613 / clean=0.613  SemanticSim=0.391 / clean=0.391  NeuroVLM-Sim=0.263
  EXPECTED : Environmental knowledge is subserved by separable dorsal/ventral neural areas.
  GENERATED: Contactins and Spatial Processing via the Right Temporoparietal Junction in Human Cognitive Function
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.524 / clean=0.502  SemanticSim=0.375 / clean=0.420  NeuroVLM-Sim=0.328
  EXPECTED : Environmental psychology models propose that knowledge of large-scale space is stored as distinct landmark (place appearance) and survey (place position) information. Studies of brain-damaged patients suffering from "topographical disorientation" tentatively support this proposal. In order to determ…
  CLEAN GT : Topographical information stored as place appearance and position, supported by patients' inability to orient. fMRI study shows dorsal/ventral dissociation between landmark appearance and survey position conditions in three out of four subjects. Agreement with human lesion studies confirms environme…
  GENERATED: Contactins are a family of cell adhesion molecules integral to neuronal development and function, including processes such as saccades and event-related potentials (P300). They play crucial roles in spatial processing, which encompasses the cognitive ability to understand and manipulate spatial info…
------------------------------------------------------------------------
[9084599]  — retrieved context:
[kg_mesh] (sim=0.413) neostriatum
  [kg_mesh] (sim=0.386) voluntary control
  [kg_mesh] (sim=0.379) spinocerebellar ataxias
  [kg_mesh] (sim=0.378) spinocerebellar tracts
  [kg_mesh] (sim=0.375) putamen
  mode=short   BERTScore-F1=0.627 / clean=0.627  SemanticSim=0.530 / clean=0.530  NeuroVLM-Sim=0.353
  EXPECTED : Anatomy of motor learning. I. Frontal cortex and attention to action.
  GENERATED: Neostriatum's Role in Motor Control and Cognitive Functions
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.511 / clean=0.479  SemanticSim=0.334 / clean=0.269  NeuroVLM-Sim=0.389
  EXPECTED : We used positron emission tomography to study new learning and automatic performance in normal volunteers. Subjects learned sequences of eight finger movements by trial and error. In a previous experiment we showed that the prefrontal cortex was activated during new learning but not during during au…
  CLEAN GT : New learning activated dorsal prefrontal cortex and anterior cingulate area 32, while automatic performance did not. Attention reactivated left dorsal prefrontal cortex and right anterior cingulate cortex during prelearned sequence performance compared to automatic performance. New learning versus a…
  GENERATED: The Neostriatum is a critical anatomical region in the brain that is involved not only in motor control but also extends to cognitive functions such as voluntary movement initiation and modulation. This region operates alongside voluntary control mechanisms, which involve conscious control over move…
------------------------------------------------------------------------
[9106283]  — retrieved context:
[kg_mesh] (sim=0.392) language control
  [kg_mesh] (sim=0.359) controlled oral
  [kg_mesh] (sim=0.355) language tasks
  [kg_mesh] (sim=0.352) aphasia, broca
  mode=short   BERTScore-F1=0.681 / clean=0.681  SemanticSim=0.363 / clean=0.363  NeuroVLM-Sim=0.383
  EXPECTED : The functional anatomy of verbal initiation and suppression using the Hayling Test.
  GENERATED: Language Control: Cognitive Framework Shaping Speech Production and Comprehension
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.503 / clean=0.444  SemanticSim=0.544 / clean=0.310  NeuroVLM-Sim=0.374
  EXPECTED : This study utilised positron emission tomography (PET) to identify the cortical areas involved in verbal initiation and suppression in normal subjects whilst performing a sentence completion test (the Hayling Test). In the first condition (response initiation) subjects were required to complete a se…
  CLEAN GT : Response initiation activated left frontal operculum, inferior frontal gyrus, middle temporal gyrus and right anterior cingulate gyrus bilaterally. Response suppression activated left frontal operculum, inferior frontal gyrus and right anterior cingulate gyrus. Increased activation in left middle te…
  GENERATED: Language control refers to the cognitive process by which individuals plan, execute, and monitor speech production, ensuring coherent and appropriate communication. This construct is closely tied to controlled oral tasks, where participants perform specific speech-related tests under strict conditio…
------------------------------------------------------------------------
[9121583]  — retrieved context:
[kg_mesh] (sim=0.406) attentional network
  [kg_mesh] (sim=0.403) executive attention
  [cogatlas] (sim=0.384) central executive
  [kg_mesh] (sim=0.380) attentional focus
  [kg_mesh] (sim=0.374) frontoparietal networks
  mode=short   BERTScore-F1=0.632 / clean=0.632  SemanticSim=0.473 / clean=0.473  NeuroVLM-Sim=0.435
  EXPECTED : Temporal dynamics of brain activation during a working memory task.
  GENERATED: The Attentional Network: Foundations in Executive Function and Frontoparietal Connectivity
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.583 / clean=0.551  SemanticSim=0.601 / clean=0.583  NeuroVLM-Sim=0.439
  EXPECTED : Working memory is responsible for the short-term storage and online manipulation of information necessary for higher cognitive functions, such as language, planning and problem-solving. Traditionally, working memory has been divided into two types of processes: executive control (governing the encod…
  CLEAN GT : Prefrontal and parietal cortices appear to be involved in active maintenance during working memory tasks as examined by fMRI.
  GENERATED: The main topic is the attentional network, a cognitive system crucial for directing and sustaining attention towards relevant stimuli, essential for various cognitive processes including perception, memory, and decision-making. The executive attention function, closely related to the attentional net…
------------------------------------------------------------------------
[9185551]  — retrieved context:
[kg_mesh] (sim=0.407) orbitofrontal
  [kg_mesh] (sim=0.403) receptors, odorant
  [kg_mesh] (sim=0.389) immunochemistry
  [kg_mesh] (sim=0.388) aphrodisiacs
  [kg_mesh] (sim=0.387) chemical phenomena
  mode=short   BERTScore-F1=0.632 / clean=0.632  SemanticSim=0.473 / clean=0.473  NeuroVLM-Sim=0.344
  EXPECTED : A role for the right anterior temporal lobe in taste quality recognition.
  GENERATED: Orbitofrontal Reward Processing and Olfactory Integration
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.537 / clean=0.534  SemanticSim=0.540 / clean=0.422  NeuroVLM-Sim=0.390
  EXPECTED : We conducted two experiments to examine central processing of the taste of citric acid. In the first experiment, elevated citric acid recognition thresholds, but normal detection thresholds, were observed in a group of patients who had undergone a right anterior temporal lobectomy for the treatment …
  CLEAN GT : Elevated citric acid recognition thresholds were observed in patients with right anterior temporal lobectomy, correlating with increased rCBF in caudolateral orbitofrontal cortex and right anteromedial temporal lobe. Right hemisphere exhibited preferential processing of higher-order gustatory functi…
  GENERATED: The orbitofrontal cortex (OFC) is a region located in the frontal lobe of the brain, subcortically adjacent to the amygdala, that plays a crucial role in reward processing and olfactory sensory integration. It interacts closely with receptors for odorant molecules on olfactory receptor neurons, whic…
------------------------------------------------------------------------
[9256495]  — retrieved context:
[kg_mesh] (sim=0.440) rivers
  [kg_mesh] (sim=0.400) starlings
  [kg_mesh] (sim=0.388) behavior observation techniques
  [kg_mesh] (sim=0.373) love
  [kg_mesh] (sim=0.366) genetic phenomena
  mode=short   BERTScore-F1=0.656 / clean=0.656  SemanticSim=0.467 / clean=0.467  NeuroVLM-Sim=0.111
  EXPECTED : Pattern of neuronal activity associated with conscious and unconscious processing of visual signals.
  GENERATED: The Neural Rivers: Connecting Brain Activity Pathways and Cognitive Functions
------------------------------------------------------------------------
  mode=long   BERTScore-F1=0.536 / clean=0.549  SemanticSim=0.364 / clean=0.403  NeuroVLM-Sim=0.262
  EXPECTED : Following striate cortex damage in monkeys and humans there can be residual function mediated by parallel visual pathways. In humans this can sometimes be associated with a "feeling" that something has happened, especially with rapid movement or abrupt onset. For less transient events, discriminativ…
  CLEAN GT : Striatocortex damage can leave residual vision mediated by parallel pathways in humans. This can be associated with a "feeling" for rapid events without conscious awareness. Even when subjects report no awareness, discriminative performance may remain above chance. We previously examined parameters …

### A.3 NeuroVault

In [ ]:
b2t_nv_records = []

for d in tqdm(neurovault_data_b2t, desc="NeuroVault B2T"):
    recs = run_b2t(
        name           = str(d["doi"]),
        latent         = d["latent"],
        short_gt       = d["short_gt"],
        long_gt        = d["long_gt"],
        short_gt_clean = d.get("short_gt_clean"),
        long_gt_clean  = d.get("long_gt_clean"),
        short_prompt   = SHORT_PROMPT_GENERAL,
        long_prompt    = LONG_PROMPT,
    )
    b2t_nv_records.extend(recs)

print(f"\nRecords collected: {len(b2t_nv_records)}")

b2t_nv_df = pd.DataFrame(b2t_nv_records)

if b2t_nv_df.empty:
    print("No records — check the [B2T error] messages above.")
else:
    display(b2t_nv_df.groupby("mode")[["bert_f1", "bert_f1_clean", "sem_sim", "sem_sim_clean", "nvlm_sim"]].mean().round(3))
    print()
    show_b2t_texts(b2t_nv_df)

### A.4 Brain-to-Text Summary

In [ ]:
b2t_net_df["dataset"]    = "networks"
b2t_pubmed_df["dataset"] = "pubmed"
b2t_nv_df["dataset"]     = "neurovault"

b2t_all = pd.concat([b2t_net_df, b2t_pubmed_df, b2t_nv_df], ignore_index=True)

summary_b2t = (
    b2t_all
    .groupby(["dataset", "mode"])[["bert_f1", "bert_f1_clean", "bert_p", "bert_r", "sem_sim", "sem_sim_clean", "nvlm_sim"]]
    .agg(["mean", "std"])
    .round(3)
)

b2t_delta_summary = (
    b2t_all
    .assign(
        bert_f1_clean_delta=lambda df: df["bert_f1_clean"] - df["bert_f1"],
        sem_sim_clean_delta=lambda df: df["sem_sim_clean"] - df["sem_sim"],
    )
    .groupby(["dataset", "mode"])[["bert_f1_clean_delta", "sem_sim_clean_delta"]]
    .agg(["mean", "std"])
    .round(3)
)

print("=== Brain-to-Text Summary (raw vs cleaned references, mean ± std) ===")
display(summary_b2t)
print("\n=== Cleaned-reference metric deltas (clean - raw, mean ± std) ===")
display(b2t_delta_summary)

### A.5 Recall@1 — Retrieval Rank

Given all N generated texts and N brain images in a dataset × mode group,
**Recall@1** measures the fraction of generated texts whose correct brain image
ranks #1 by `nvlm_sim` over all other brain images.

| Score | Interpretation |
|---|---|
| `1/N` | Chance level (random assignment) |
| `> 2/N` | Better than chance |
| `1.0` | Every generated text uniquely identifies its source brain |

In [ ]:
def recall_at_1(df: pd.DataFrame) -> float:
    """
    Given N (brain, generated_text) pairs, compute the fraction where
    the brain's own generated text scores highest among all texts.
    Chance level = 1/N.
    """
    brain_embs = torch.stack([e.squeeze(0) for e in df["_brain_query_emb"].tolist()])
    nvlm._ensure_projection_heads()
    with torch.no_grad():
        texts    = df["generated"].tolist()
        raw_embs = torch.cat([nvlm._encode_text(t) for t in texts], dim=0)
        z_texts  = nvlm._proj_head_text_infonce(raw_embs.to(nvlm.device))
        z_texts  = F.normalize(z_texts, dim=-1).cpu()
    z_brains   = F.normalize(brain_embs, dim=-1)
    sim_matrix = z_brains @ z_texts.T
    ranks      = (sim_matrix > sim_matrix.diag().unsqueeze(1)).sum(dim=1)
    return float((ranks == 0).float().mean())


# ── Brain query embeddings (fast — no LLM call) ──────────────────────────
print("Computing Recall@1 ...")

brain_emb_cache = {}

def _get_brain_query_emb(name, latent):
    if name not in brain_emb_cache:
        r = nvlm.brain(latent).to_text(datasets=B2T_DATASETS)
        brain_emb_cache[name] = r.query_embeddings
    return brain_emb_cache[name]

_all_latents = {}
for k, d in networks_data.items():
    _all_latents[k] = d["latent"]
for d in pubmed_data_b2t:
    _all_latents[str(d["pmid"])] = d["latent"]
for d in neurovault_data_b2t:
    _all_latents[str(d["doi"])]  = d["latent"]

b2t_all["_brain_query_emb"] = b2t_all["name"].map(
    lambda n: _get_brain_query_emb(n, _all_latents[n])
)

# ── Recall@1 per dataset × mode ───────────────────────────────────────────
r1_rows = []
for (ds, mode), grp in b2t_all.groupby(["dataset", "mode"]):
    grp   = grp.reset_index(drop=True)
    n     = len(grp)
    r1    = recall_at_1(grp)
    chance = round(1 / n, 3)
    r1_rows.append({"dataset": ds, "mode": mode,
                    "N": n, "chance": chance, "recall@1": round(r1, 3)})

b2t_recall1 = pd.DataFrame(r1_rows).set_index(["dataset", "mode"])

print("\n=== Recall@1 ===")
print("  recall@1=1/N means chance; recall@1=1.0 means perfect")
display(b2t_recall1)

In [ ]:
datasets  = ["networks", "pubmed", "neurovault"]
modes     = ["short", "long"]
metrics   = ["nvlm_sim", "bert_f1", "bert_f1_clean", "sem_sim", "sem_sim_clean"]
m_labels  = ["NeuroVLM Latent Sim", "BERTScore F1", "BERTScore F1 (Clean GT)",
             "Semantic Sim", "Semantic Sim (Clean GT)"]

fig, axes = plt.subplots(1, 5, figsize=(24, 4), sharey=False)
x      = np.arange(len(datasets))
w      = 0.35
colors = {"short": "steelblue", "long": "darkorange"}

for ax, metric, m_label in zip(axes, metrics, m_labels):
    for j, mode in enumerate(modes):
        vals = [
            b2t_all[(b2t_all["dataset"] == ds) & (b2t_all["mode"] == mode)][metric].mean()
            for ds in datasets
        ]
        offset = (j - 0.5) * w
        bars = ax.bar(x + offset, vals, w, label=mode,
                      color=colors[mode], alpha=0.85, edgecolor="white")
        ax.bar_label(bars, fmt="%.3f", padding=2, fontsize=7)

    ax.set_xticks(x)
    ax.set_xticklabels(datasets, rotation=15, ha="right")
    ax.set_title(m_label, fontsize=10)
    ax.set_ylabel("Score")
    ax.set_ylim(0, min(1.05, max(0.1, ax.get_ylim()[1] * 1.25)))
    ax.legend(fontsize=8)
    ax.grid(axis="y", alpha=0.3)

axes[0].set_facecolor("#fff7e6")
axes[0].text(0.02, 0.95, "domain-specific", transform=axes[0].transAxes,
             fontsize=8, va="top", bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="orange", lw=0.8))

fig.suptitle("Brain-to-Text Generation Quality: Raw vs Cleaned References",
             fontsize=13, fontweight="bold")
fig.tight_layout()
plt.savefig("b2t_metrics_v2.png", dpi=150, bbox_inches="tight")
plt.show()

In [ ]:
# NeuroVLM latent sim vs BERTScore F1 scatter — the domain-specific vs general-purpose comparison
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

ds_colors  = {"networks": "C0", "pubmed": "C1", "neurovault": "C2"}
ds_markers = {"short": "o", "long": "s"}

for ax, mode in zip(axes, modes):
    sub = b2t_all[b2t_all["mode"] == mode]
    for ds in datasets:
        rows = sub[sub["dataset"] == ds]
        ax.scatter(rows["bert_f1"], rows["nvlm_sim"],
                   s=40, alpha=0.5, color=ds_colors[ds], label=ds,
                   marker=ds_markers[mode])
        ax.scatter(rows["bert_f1"].mean(), rows["nvlm_sim"].mean(),
                   s=180, color=ds_colors[ds], marker="*", zorder=5,
                   edgecolors="black", linewidths=0.5)

    ax.set_xlim(0, 1.05)
    ax.set_ylim(-0.1, 1.05)
    ax.axhline(0, color="grey", lw=0.5, ls="--")
    ax.set_xlabel("BERTScore F1")
    ax.set_ylabel("NeuroVLM Latent Similarity")
    ax.set_title(f"B2T: BERTScore F1 vs NeuroVLM Sim — {mode} mode (★ = dataset mean)")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.2)

fig.tight_layout()
plt.savefig("b2t_bertscore_vs_nvlm.png", dpi=150, bbox_inches="tight")
plt.show()

---
## Part B — Text-to-Brain (Pearson r, Spearman ρ, Dice pct-90, Spin-test p-value)

For each text input we:
1. Generate a predicted brain activation map via `nvlm.text(input).to_brain(head="mse")`.
2. Decode the ground-truth latent through the same autoencoder decoder.
3. Compare with spatial metrics aligned to the NCT reporting style.

**Metrics:**
- **Percentile Dice** (pct=90): thresholds both maps at their own 90th-percentile activation.
- **Spin-test p-value**: projects MNI152 volume maps to fsaverage6/41k using `neuromaps.transforms.mni152_to_fsaverage`, then uses `brainspace.null_models.spin.SpinPermutations` for 1000 rotations. This matches the NCT-style surface-spin significance workflow without reimplementing Wu et al. (2018) registrations.
- **Pearson r / Spearman ρ**: secondary diagnostics for intensity and rank alignment.

PSNR and Top-k overlap are intentionally removed from the primary T2B table.

In [ ]:
def run_t2b(name, text_input, true_latent):
    try:
        # --- Predicted brain map ------------------------------------------
        gen_result  = nvlm.text(text_input).to_brain(head="mse")
        nifti_pred  = gen_result.to_nifti(index=0)
        brain_pred  = masker.transform(nifti_pred).ravel().astype("float32")

        # --- Ground-truth map via same decoder ----------------------------
        dec        = gen_result.decoder
        dec_device = next(dec.parameters()).device
        lat        = true_latent
        if lat.dim() == 1:
            lat = lat.unsqueeze(0)
        with torch.no_grad():
            brain_true = (
                torch.sigmoid(dec(lat.to(dec_device)))
                .squeeze(0).cpu().numpy()
            )
        nifti_true = masker.inverse_transform(brain_true.reshape(1, -1))

        # --- Metrics ------------------------------------------------------
        pearson_r = float(pearson_correlation(brain_true, brain_pred))
        spearman_rho, _ = spearmanr(brain_true.ravel(), brain_pred.ravel())
        dice_p90 = dice_percentile(brain_pred, brain_true, pct=DICE_PCT)
        dice_method = "volume_masker_percentile_fallback"

        pred_lh = pred_rh = true_lh = true_rh = None
        if SPIN_USE_NEUROMAPS:
            try:
                pred_lh, pred_rh = mni152_to_fsaverage_arrays(
                    nifti_pred,
                    density=SPIN_FSAVERAGE_DENSITY,
                    method=SPIN_TRANSFORM_METHOD,
                )
                true_lh, true_rh = mni152_to_fsaverage_arrays(
                    nifti_true,
                    density=SPIN_FSAVERAGE_DENSITY,
                    method=SPIN_TRANSFORM_METHOD,
                )
                nct = nct_dice_spin_test_surface(
                    pred_lh,
                    pred_rh,
                    true_lh,
                    true_rh,
                    pct=DICE_PCT,
                    n_perm=SPIN_TEST_N_PERM,
                    random_state=SPIN_TEST_RANDOM_STATE,
                    density=SPIN_FSAVERAGE_DENSITY,
                )
                dice_p90 = nct.dice_pct
                dice_method = "surface_fsaverage_percentile_nct"
                spin_p_value = nct.spin_p_value
                spin_method = nct.spin_method
                spin_significant = nct.spin_significant
            except ImportError as e:
                spin_p_value = np.nan
                spin_method = f"not_run_missing_dependency:{e.name}"
                spin_significant = False
            except Exception as e:
                spin_p_value = np.nan
                spin_method = f"not_run_nct_error:{type(e).__name__}: {e}"
                spin_significant = False
        else:
            spin_p_value = np.nan
            spin_method = "disabled"
            spin_significant = False

        return {
            "name":         name,
            "text_input":   text_input[:80],
            "pearson_r":    pearson_r,
            "spearman_rho": float(spearman_rho),
            "dice_pct90":   float(dice_p90),
            "dice_method":  dice_method,
            "spin_p_value": float(spin_p_value) if np.isfinite(spin_p_value) else np.nan,
            "spin_significant": bool(spin_significant),
            "spin_method": spin_method,
            "_brain_pred": brain_pred,
            "_brain_true": brain_true,
            "_pred_lh": pred_lh,
            "_pred_rh": pred_rh,
            "_true_lh": true_lh,
            "_true_rh": true_rh,
        }

    except Exception as e:
        print(f"  [T2B error] {name}: {e}")
        return None

### B.1 Networks

Text input = long network description.  
Ground truth = Du atlas network latent.

In [ ]:
t2b_networks_records = []

for net_name, d in tqdm(networks_data.items(), desc="Networks T2B"):
    rec = run_t2b(
        name        = net_name,
        text_input  = d["long_gt"],
        true_latent = d["latent"],
    )
    if rec is not None:
        t2b_networks_records.append(rec)

t2b_net_df = pd.DataFrame(t2b_networks_records).set_index("name")

display_cols = ["pearson_r", "spearman_rho", "dice_pct90", "dice_method", "spin_p_value", "spin_significant", "spin_method"]
t2b_net_df[display_cols].round(3)

### B.2 PubMed

Text input = title + " [SEP] " + abstract.  
Ground truth = pre-encoded PubMed brain image latent.

In [ ]:
t2b_pubmed_records = []

for d in tqdm(pubmed_data_t2b, desc="PubMed T2B"):
    text_in = d["short_gt"] + " [SEP] " + d["long_gt"]
    rec = run_t2b(
        name        = str(d["pmid"]),
        text_input  = text_in,
        true_latent = d["latent"],
    )
    if rec is not None:
        t2b_pubmed_records.append(rec)

t2b_pubmed_df = pd.DataFrame(t2b_pubmed_records)

print(f"PubMed T2B — {len(t2b_pubmed_df)} samples evaluated")
t2b_pubmed_df[["pearson_r", "spearman_rho", "dice_pct90", "spin_p_value"]].describe().round(3)

### B.3 NeuroVault

Text input = title + " [SEP] " + abstract.  
Ground truth = pre-encoded NeuroVault brain image latent.

In [ ]:
t2b_nv_records = []

for d in tqdm(neurovault_data_t2b, desc="NeuroVault T2B"):
    text_in = d["short_gt"] + " [SEP] " + d["long_gt"]
    rec = run_t2b(
        name        = str(d["doi"]),
        text_input  = text_in,
        true_latent = d["latent"],
    )
    if rec is not None:
        t2b_nv_records.append(rec)

t2b_nv_df = pd.DataFrame(t2b_nv_records)

print(f"NeuroVault T2B — {len(t2b_nv_df)} samples evaluated")
t2b_nv_df[["pearson_r", "spearman_rho", "dice_pct90", "spin_p_value"]].describe().round(3)

### B.4 Text-to-Brain Summary

In [ ]:
t2b_net_df_flat = t2b_net_df.reset_index().rename(columns={"name": "sample"})
t2b_net_df_flat["dataset"] = "networks"
t2b_pubmed_df["dataset"]   = "pubmed"
t2b_nv_df["dataset"]       = "neurovault"

t2b_all = pd.concat(
    [t2b_net_df_flat, t2b_pubmed_df, t2b_nv_df],
    ignore_index=True
)

t2b_metric_cols = ["pearson_r", "spearman_rho", "dice_pct90", "spin_p_value"]

summary_t2b = (
    t2b_all
    .groupby("dataset")[t2b_metric_cols]
    .agg(["mean", "std"])
    .round(3)
)

spin_sig_summary = (
    t2b_all
    .groupby("dataset")["spin_significant"]
    .sum()
    .rename("n_spin_p_lt_0_05")
)

print("=== Text-to-Brain Summary (mean ± std) ===")
display(summary_t2b)
print("\n=== Spin-test significant samples (p < 0.05) ===")
display(spin_sig_summary)
print("\nSpin method counts:")
display(t2b_all.groupby(["dataset", "spin_method"]).size().rename("n"))

### B.5 Dice Threshold Sensitivity

Compare top-activation overlap across multiple percentile thresholds. `pct=80` compares the top 20% of each map, `pct=90` compares the top 10%, and `pct=95` compares the top 5%. Spin p-values are recomputed at each threshold when fsaverage surface maps are available.

In [ ]:
def _sensitivity_rows_for_df(df: pd.DataFrame, dataset: str, pcts=DICE_SENSITIVITY_PCTS):
    rows = []
    for _, row in tqdm(df.reset_index().iterrows(), total=len(df), desc=f"{dataset} sensitivity"):
        sample = row.get("name", row.get("sample", row.get("index", "?")))
        has_surface = all(row.get(k) is not None for k in ["_pred_lh", "_pred_rh", "_true_lh", "_true_rh"])
        for pct in pcts:
            if has_surface:
                try:
                    nct = nct_dice_spin_test_surface(
                        row["_pred_lh"],
                        row["_pred_rh"],
                        row["_true_lh"],
                        row["_true_rh"],
                        pct=pct,
                        n_perm=SPIN_TEST_N_PERM,
                        random_state=SPIN_TEST_RANDOM_STATE,
                        density=SPIN_FSAVERAGE_DENSITY,
                    )
                    dice_val = nct.dice_pct
                    spin_p = nct.spin_p_value
                    spin_sig = nct.spin_significant
                    method = "surface_fsaverage_percentile_nct"
                    spin_method = nct.spin_method
                except Exception as e:
                    dice_val = dice_percentile(row["_brain_pred"], row["_brain_true"], pct=pct)
                    spin_p = np.nan
                    spin_sig = False
                    method = "volume_masker_percentile_fallback"
                    spin_method = f"not_run_nct_error:{type(e).__name__}: {e}"
            else:
                dice_val = dice_percentile(row["_brain_pred"], row["_brain_true"], pct=pct)
                spin_p = np.nan
                spin_sig = False
                method = "volume_masker_percentile_fallback"
                spin_method = row.get("spin_method", "not_run_no_surface_maps")

            rows.append({
                "dataset": dataset,
                "sample": sample,
                "pct": pct,
                "top_fraction": (100 - pct) / 100,
                "dice": float(dice_val),
                "spin_p_value": float(spin_p) if np.isfinite(spin_p) else np.nan,
                "spin_significant": bool(spin_sig),
                "dice_method": method,
                "spin_method": spin_method,
            })
    return rows


t2b_sensitivity_records = []
t2b_sensitivity_records.extend(_sensitivity_rows_for_df(t2b_net_df.reset_index(), "networks"))
t2b_sensitivity_records.extend(_sensitivity_rows_for_df(t2b_pubmed_df, "pubmed"))
t2b_sensitivity_records.extend(_sensitivity_rows_for_df(t2b_nv_df, "neurovault"))

t2b_sensitivity_df = pd.DataFrame(t2b_sensitivity_records)

t2b_sensitivity_summary = (
    t2b_sensitivity_df
    .groupby(["dataset", "pct"])
    .agg(
        dice_mean=("dice", "mean"),
        dice_std=("dice", "std"),
        spin_p_median=("spin_p_value", "median"),
        spin_p_lt_0_05=("spin_significant", "mean"),
        n=("sample", "count"),
    )
    .round(3)
)

print("=== T2B Dice / Spin Sensitivity by Threshold ===")
display(t2b_sensitivity_summary)
print("\nMethod counts:")
display(t2b_sensitivity_df.groupby(["dataset", "pct", "dice_method"]).size().rename("n"))

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(12, 4))

summary_plot = t2b_sensitivity_df.groupby(["dataset", "pct"]).agg(
    dice_mean=("dice", "mean"),
    dice_sem=("dice", lambda x: x.std() / np.sqrt(len(x))),
    sig_rate=("spin_significant", "mean"),
).reset_index()

for ds, c in zip(["networks", "pubmed", "neurovault"], ["C0", "C1", "C2"]):
    sub = summary_plot[summary_plot["dataset"] == ds]
    axes[0].errorbar(sub["pct"], sub["dice_mean"], yerr=sub["dice_sem"], marker="o", color=c, label=ds)
    axes[1].plot(sub["pct"], sub["sig_rate"], marker="o", color=c, label=ds)

axes[0].set_xlabel("Percentile threshold")
axes[0].set_ylabel("Mean Dice")
axes[0].set_title("T2B Dice Sensitivity")
axes[0].grid(alpha=0.25)
axes[0].legend()

axes[1].set_xlabel("Percentile threshold")
axes[1].set_ylabel("Fraction p < 0.05")
axes[1].set_ylim(-0.05, 1.05)
axes[1].set_title("Spin-Test Significance Rate")
axes[1].grid(alpha=0.25)
axes[1].legend()

fig.tight_layout()
plt.savefig("t2b_dice_threshold_sensitivity.png", dpi=150, bbox_inches="tight")
plt.show()

In [ ]:
ds_order   = ["networks", "pubmed", "neurovault"]
t2b_cols   = ["pearson_r", "spearman_rho", "dice_pct90", "spin_p_value"]
t2b_labels = ["Pearson r", "Spearman ρ", f"Dice (pct={DICE_PCT})", "Spin-test p-value"]
ds_colors  = ["C0", "C1", "C2"]

fig, axes = plt.subplots(1, 4, figsize=(18, 4), sharey=False)
x = np.arange(len(ds_order))

for ax, metric, m_label in zip(axes, t2b_cols, t2b_labels):
    means = [t2b_all[t2b_all["dataset"] == ds][metric].mean() for ds in ds_order]
    stds  = [t2b_all[t2b_all["dataset"] == ds][metric].std()  for ds in ds_order]
    bars  = ax.bar(x, means, color=ds_colors, alpha=0.85, edgecolor="white",
                   yerr=stds, capsize=4, error_kw={"linewidth": 1})
    ax.bar_label(bars, fmt="%.3f", padding=3, fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels(ds_order, rotation=15, ha="right")
    ax.set_title(m_label)
    ax.set_ylabel("Score")
    ax.grid(axis="y", alpha=0.3)
    if metric == "spin_p_value":
        ax.axhline(0.05, color="crimson", linestyle="--", linewidth=1)

fig.suptitle("Text-to-Brain Generation Quality by Dataset",
             fontsize=13, fontweight="bold")
fig.tight_layout()
plt.savefig("t2b_metrics_v2.png", dpi=150, bbox_inches="tight")
plt.show()

In [ ]:
# Pearson r vs Spearman ρ scatter — coloured by dataset
fig, ax = plt.subplots(figsize=(7, 5))

for ds, c in zip(ds_order, ds_colors):
    sub = t2b_all[t2b_all["dataset"] == ds]
    ax.scatter(sub["pearson_r"], sub["spearman_rho"],
               s=40, alpha=0.55, color=c, label=ds)
    ax.scatter(sub["pearson_r"].mean(), sub["spearman_rho"].mean(),
               s=200, color=c, marker="*", zorder=5,
               edgecolors="black", linewidths=0.5)

lim_min = min(t2b_all[["pearson_r", "spearman_rho"]].min()) - 0.05
lim_max = max(t2b_all[["pearson_r", "spearman_rho"]].max()) + 0.05
ax.plot([lim_min, lim_max], [lim_min, lim_max], "--", color="grey", lw=0.8, alpha=0.5)

ax.set_xlabel("Pearson r")
ax.set_ylabel("Spearman ρ")
ax.set_title("Text-to-Brain: Pearson r vs Spearman ρ (★ = dataset mean)")
ax.legend()
ax.grid(alpha=0.25)
fig.tight_layout()
plt.savefig("t2b_pearson_vs_spearman.png", dpi=150, bbox_inches="tight")
plt.show()

---
## Full Evaluation Summary

In [ ]:
print("\n" + "="*65)
print("BRAIN-TO-TEXT  (mean across samples)")
print("="*65)
print(
    b2t_all
    .groupby(["dataset", "mode"])[["nvlm_sim", "bert_f1", "bert_f1_clean", "sem_sim", "sem_sim_clean"]]
    .mean()
    .round(4)
    .to_string()
)

print("\nB2T cleaned-reference deltas (clean - raw):")
print(
    b2t_all
    .assign(
        bert_f1_clean_delta=lambda df: df["bert_f1_clean"] - df["bert_f1"],
        sem_sim_clean_delta=lambda df: df["sem_sim_clean"] - df["sem_sim"],
    )
    .groupby(["dataset", "mode"])[["bert_f1_clean_delta", "sem_sim_clean_delta"]]
    .mean()
    .round(4)
    .to_string()
)

print("\n" + "="*65)
print("TEXT-TO-BRAIN  (spatial metrics mean across samples)")
print("="*65)
print(
    t2b_all
    .groupby("dataset")[["pearson_r", "spearman_rho", "dice_pct90", "spin_p_value"]]
    .mean()
    .round(4)
    .to_string()
)

print("\nSpin-test significant counts (p < 0.05):")
print(t2b_all.groupby("dataset")["spin_significant"].sum().to_string())
print("\nSpin method counts:")
print(t2b_all.groupby(["dataset", "spin_method"]).size().to_string())


if "t2b_sensitivity_summary" in globals():
    print("\n" + "="*65)
    print("T2B DICE THRESHOLD SENSITIVITY")
    print("="*65)
    print(t2b_sensitivity_summary.to_string())